---
# Lamp setup for Word installation
   - name: Apache/Mysql/PHP installation
     apt: name={{ item }} state=present
     with_items:
      - apache2
      - mariadb-server
      - python3-mysqldb
      - php7.4-mysql
      - php7.4
      - libapache2-mod-php7.4
      - python3-mysqldb
     notify: restart apache

   - name: start apache2
     ansible.builtin.service:
      name: apache2
      state: restarted

   - name: restart mariadb
     ansible.builtin.service:
      name: mariadb
      state: restarted 

   - name: Install php extensions
     apt: name={{ item }} state=present
     with_items:
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-mysqlnd
      - php7.4-mysqli
      - php7.4-curl
      - php7.4-zip
      - php7.4-readline
      - php7.4-tidy

   - name: Database creation
     mysql_db:
      login_user: root
      login_password: "P@word123"
      name: wp1
      state: present
     become: yes

   - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
     community.mysql.mysql_user:
      name: wpuser
      password: wp@1234
      priv: '*.*:ALL,GRANT'
      state: present

   - name: Download and unzip wordpress
     ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      remote_src: yes

   - name: Copy sample config file
     command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php creates=/var/www/html/wordpress/wp-config.php
     notify: restart apache

   - name: Update Database name
     replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      replace: "wp1"


   - name: Update Database user
     replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'username_here'
      replace: "wpuser"

   - name: Update database user password
     replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'password_here'
      replace: "wp@1234"
     notify: restart apache
